build:
	javac Tema2.java CoordThread.java MapCallable.java MapResult.java ReduceResult.java ReduceCallable.java
run:
	java Tema2 4 ../tests/in/test0.txt out
clean:
	rm Tema2.class CoordThread.class MapCallable.class MapResult.class ReduceResult.class ReduceCallable.class